#!/usr/bin/perl

print "What is your name?";
chomp($name = <STDIN>);

print "Welcome, $name, are you ready to learn Perl now? ";

chomp($response = <STDIN>);
$response = lc($response);

if ($response eq "yes" or $response eq "y") {
    print "Great! Let's get started learning Perl by example.\n";
} else {
    print "O.K. Try again later. \n";
}

$now = localtime;
print "$name, you run this script on $now .\n";
