#!/bin/sh

get_config() {
  git config --list
}

most_recent_commit() {
 # git log --max-count=1 --pretty=short
 git log --max-count=1 --color --graph \
 --pretty=format:"%Cred%h%Creset -%C(yellow)%Creset %s \
%Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit -- 
}

local_branches() {
  git branch
}

remote_branches() {
  git branch -r
}

remote_urls() {
  git remote -v
}

# Show info similar to svn

echo
echo "## Remote URLs:"
echo "$(remote_urls)"

echo "## Remote Branches:"
echo "$(remote_branches)"

echo "## Local Branches:"
echo "$(local_branches)"

echo "## Most Recent Commit:"
echo "$(most_recent_commit)"
echo "Type 'git log' for more commits, or 'git show <commit id>' for full commit details."

if test "$1" != "--no-config"; then
  echo "## Configuration (.git/config):"
  echo "$(get_config)"
fi
