#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

my $project;
my $path = `pwd`;
my $commit = '';
my $file ="/tmp/lines.txt";

$project = basename($path);

#
# 获取建立仓库的时间
#
sub repository_age {
    `git log --pretty=oneline --format="%ar" | tail -n1 | sed 's/ago/ /'`;
}

sub active_days {
    `git log --pretty='format %ai' | cut -d ' ' -f 2 | uniq | wc -l`;
}

#
# get the commit total
#
sub commit_count{
    `git log --oneline $commit | wc -l`;
}

#
# get the file total
#
sub file_count {
    `git ls-files | wc -l`;
}

#
# list authors
#
sub author {
    my @author = `git log --pretty='format:%an' | sort -r | uniq`;
    my @log =  `git shortlog -n -s $commit`; 
    my @commits;
    my $total = 0;
    my @tmp;
    my $i  = 0;
    my $plus = 0;
    my $minus = 0;

    chomp(@log);
    chomp(@author);
    foreach (@author) {
        $commits[$i++] = `git log --oneline --author=$_  | wc -l | tr -d ' '`;
    }

    @tmp= `git rev-list --all`;
    $total = @tmp;
    chomp(@commits);
    $i = 0;
    foreach (@commits) {
        # 显示每位作者commits的数量
        printf "\e[36m  %-10s\t%-d(%2.1f%%)\t      \e[0m", 
                           $author[$i], $commits[$i], 100*$commits[$i]/$total;

        # 统计每位作者添加/删除代码的行数.
        `git log --numstat --oneline  --pretty=format:"" --author=$author[$i]  > $file`;
        open LINES , "< $file" or die "can't open file! \n";

        $plus = 0;
        $minus = 0;
        while(<LINES>) {
            if ($_ =~ /(?<plus>\d+)\s+(?<minus>\d+)/ ) {
                $plus += $+{plus};
                $minus += $+{minus};
            }   
        } 
        printf "\e[36m%-d\t%-d\e[0m \n", $plus, $minus;
        $i++;
    }
}

my $repo_age = &repository_age;
my $active_days = &active_days;
my $commit_count = &commit_count;
my $file_count = &file_count;

chomp($active_days);

print "\n\e[32mproject  : $project";
print "\e[32mrepo age : $repo_age";
print "\e[32mactive   : $active_days days\e[0m\n";
print "\e[32mcommits  : $commit_count\e[0m";

$commit = shift @ARGV;
if (!defined $commit) {
    $commit = '';
    print "\e[32mfiles    : $file_count\e[0m";
}

print "  Author\tCommits  \t+lines\t\t-lines: \n";
&author;
system('rm -rf /tmp/lines.txt');
