#!/usr/bin/perl

use strict;
use warnings;

my %AoH = (
    {
        husband    => "barney",
        wife       => "betty",
        son        => "bamm bamm",
    },
    {
        husband    => "george",
        wife       => "jane",
        son        => "elroy",
    },
    {
        husband    => "homer",
        wife       => "marge",
        son        => "bart",
    },
);

push @AoH,{
        husband    => "fred",
        wife       => "wilma",
        daughter   => "pebbles",
};
