#!/usr/bin/perl

use strict;
use warnings;

my %HoA = (
    flintstones    => ["fred","barney"],
    jetsons        => ["george","jane","elroy"],
    simpsons       => ["homer","marge","bart"],
);

my $family = 0;
my $i;
=pon
foreach $family (keys %HoA) {
    print "$family:@{$HoA{$family}} \n";
}
=cut

foreach $family (keys %HoA) {
    print "$family:\n";
    for $i (0 .. $#{$HoA{$family}}) {
        print "$i = $HoA{$family}[$i]";
    }
    print "\n";
}

