#!/usr/bin/perl

use strict;
use warnings;

use Horse;

my $steed = Horse->new(
    name    => "shadowfax",
    color   => "white"
);

my $ed = Horse->new;
my $stallion = Horse->new(color    => "black");

#$stallion->__print();
