#!/usr/bin/perl

use strict;
use warnings;

use Horse;

#my $ed = Horse->new;
#my $stallion = Horse->new(color => "black");

#$stallion->__print();


my $steed = Horse->new(color =>"dun");
my $foal = $steed->clone(owner => "EquuGen Guild,Ltd");
#my $test = Horse->__print("Hello"); 
